/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Rangora
 */
public class v_dalamKandang extends javax.swing.JFrame {

    /**
     * Creates new form v_dalamKandang
     */
    public v_dalamKandang() {
        initComponents();
        this.setLocationRelativeTo(this);
        sapi0.setActionCommand("sapi0");
        sapi1.setActionCommand("sapi1");
        sapi2.setActionCommand("sapi2");
        sapi3.setActionCommand("sapi3");
        sapi4.setActionCommand("sapi4");
        sapi5.setActionCommand("sapi5");
        sapi6.setActionCommand("sapi6");
        tempatMakan1.setActionCommand("tempat1");
        tempatMakan2.setActionCommand("tempat2");
        tempatMakan3.setActionCommand("tempat3");
        tempatMakan4.setActionCommand("tempat4");
        tempatMakan5.setActionCommand("tempat5");
        tempatMakan6.setActionCommand("tempat6");
        susuBtn.setActionCommand(1+"");
        susuBtn1.setActionCommand(2+"");
        susuBtn2.setActionCommand(3+"");
        susuBtn3.setActionCommand(4+"");
        susuBtn4.setActionCommand(5+"");
        susuBtn5.setActionCommand(6+"");
        for (int i = 0; i < 6; i++) {
            susu()[i].setVisible(false);
        }
    }

    public JButton[] susu() {
        JButton[] susu = new JButton[6];
        susu[0] = susuBtn;
        susu[1] = susuBtn1;
        susu[2] = susuBtn2;
        susu[3] = susuBtn3;
        susu[4] = susuBtn4;
        susu[5] = susuBtn5;
        return susu;
    }

    public JButton rumputSapi() {
        return makanBtn;
    }

    public JButton airSapi() {
        return airBtn;
    }

    public JButton suntikSapi() {
        return suntikBtn;
    }

    public JButton obatSapi() {
        return obatBtn;
    }

    public JButton nutrisiSapi() {
        return nutrisiBtn;

    }

    public JLabel[] getLapar() {
        JLabel lapar[] = new JLabel[6];
        lapar[0] = laparStat;
        lapar[1] = laparStat1;
        lapar[2] = laparStat2;
        lapar[3] = laparStat3;
        lapar[4] = laparStat4;
        lapar[5] = laparStat5;
        return lapar;
    }

    public JLabel[] getSakit() {
        JLabel sakit[] = new JLabel[6];
        sakit[0] = sakitStat;
        sakit[1] = sakitStat1;
        sakit[2] = sakitStat2;
        sakit[3] = sakitStat3;
        sakit[4] = sakitStat4;
        sakit[5] = sakitStat5;
        return sakit;
    }

    public JButton[] sapiButton() {
        JButton sapi[] = new JButton[7];
        sapi[0] = sapi0;
        sapi[1] = sapi1;
        sapi[2] = sapi2;
        sapi[3] = sapi3;
        sapi[4] = sapi4;
        sapi[5] = sapi5;
        sapi[6] = sapi6;
        return sapi;
    }

    public JButton[] tempatMakanButton() {
        JButton tempat[] = new JButton[7];
        tempat[0] = tempatMakan0;
        tempat[1] = tempatMakan1;
        tempat[2] = tempatMakan2;
        tempat[3] = tempatMakan3;
        tempat[4] = tempatMakan4;
        tempat[5] = tempatMakan5;
        tempat[6] = tempatMakan6;
        return tempat;
    }

    public JButton homeButton() {
        return homeButton;
    }

    public int setRumput(int text) {
        this.rumputCounter.setText(text + "");
        return text;
    }

    public int setNutrisi(int text) {
        this.nutrisiCounter.setText(text + "");
        return text;
    }

    public int setSuntikan(int text) {
        this.suntikanCounter.setText(text + "");
        return text;
    }

    public int setObat(int text) {
        this.obatCounter.setText(text + "");
        return text;
    }

    public int setSusu(int text) {
        this.susuLabel.setText(text + "");
        return text;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconsusu = new javax.swing.JLabel();
        iconsusu2 = new javax.swing.JLabel();
        rumputCounter = new javax.swing.JLabel();
        obatCounter = new javax.swing.JLabel();
        iconsusu1 = new javax.swing.JLabel();
        iconsusu3 = new javax.swing.JLabel();
        iconsusu4 = new javax.swing.JLabel();
        susuLabel = new javax.swing.JLabel();
        nutrisiCounter = new javax.swing.JLabel();
        suntikanCounter = new javax.swing.JLabel();
        statusBar = new javax.swing.JLabel();
        sakitStat2 = new javax.swing.JLabel();
        laparStat2 = new javax.swing.JLabel();
        sakitStat3 = new javax.swing.JLabel();
        laparStat3 = new javax.swing.JLabel();
        sakitStat4 = new javax.swing.JLabel();
        laparStat4 = new javax.swing.JLabel();
        sakitStat5 = new javax.swing.JLabel();
        laparStat5 = new javax.swing.JLabel();
        sakitStat1 = new javax.swing.JLabel();
        laparStat1 = new javax.swing.JLabel();
        laparStat = new javax.swing.JLabel();
        sakitStat = new javax.swing.JLabel();
        susuBtn1 = new javax.swing.JButton();
        susuBtn2 = new javax.swing.JButton();
        susuBtn3 = new javax.swing.JButton();
        susuBtn4 = new javax.swing.JButton();
        susuBtn5 = new javax.swing.JButton();
        susuBtn = new javax.swing.JButton();
        suntikBtn = new javax.swing.JButton();
        obatBtn = new javax.swing.JButton();
        nutrisiBtn = new javax.swing.JButton();
        airBtn = new javax.swing.JButton();
        makanBtn = new javax.swing.JButton();
        tempatMakan6 = new javax.swing.JButton();
        tempatMakan5 = new javax.swing.JButton();
        tempatMakan4 = new javax.swing.JButton();
        tempatMakan3 = new javax.swing.JButton();
        tempatMakan2 = new javax.swing.JButton();
        tempatMakan1 = new javax.swing.JButton();
        tempatMakan0 = new javax.swing.JButton();
        sapi0 = new javax.swing.JButton();
        sapi6 = new javax.swing.JButton();
        sapi5 = new javax.swing.JButton();
        sapi4 = new javax.swing.JButton();
        sapi3 = new javax.swing.JButton();
        sapi2 = new javax.swing.JButton();
        sapi1 = new javax.swing.JButton();
        tulisanExit = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 730));
        setUndecorated(true);
        getContentPane().setLayout(null);

        iconsusu.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        iconsusu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconsusu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/medic Cilik.png"))); // NOI18N
        getContentPane().add(iconsusu);
        iconsusu.setBounds(980, 20, 50, 40);

        iconsusu2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        iconsusu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconsusu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/suntik Cilik.png"))); // NOI18N
        getContentPane().add(iconsusu2);
        iconsusu2.setBounds(760, 20, 50, 40);

        rumputCounter.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        rumputCounter.setText("rumputStatus");
        getContentPane().add(rumputCounter);
        rumputCounter.setBounds(920, 30, 40, 20);

        obatCounter.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        obatCounter.setText("obatStatus");
        getContentPane().add(obatCounter);
        obatCounter.setBounds(1030, 30, 40, 20);

        iconsusu1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        iconsusu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconsusu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/susu cilik.png"))); // NOI18N
        getContentPane().add(iconsusu1);
        iconsusu1.setBounds(670, 20, 50, 40);

        iconsusu3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        iconsusu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconsusu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nutrisi Cilik.png"))); // NOI18N
        getContentPane().add(iconsusu3);
        iconsusu3.setBounds(1100, 20, 50, 40);

        iconsusu4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        iconsusu4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconsusu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rumput cilik.png"))); // NOI18N
        getContentPane().add(iconsusu4);
        iconsusu4.setBounds(870, 20, 50, 40);

        susuLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        susuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        susuLabel.setText("susu");
        getContentPane().add(susuLabel);
        susuLabel.setBounds(700, 20, 60, 40);

        nutrisiCounter.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        nutrisiCounter.setText("nutrisiStatus");
        getContentPane().add(nutrisiCounter);
        nutrisiCounter.setBounds(1150, 30, 30, 20);

        suntikanCounter.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        suntikanCounter.setText("jLabel3");
        getContentPane().add(suntikanCounter);
        suntikanCounter.setBounds(810, 30, 45, 20);

        statusBar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/status bar dalam kandang_1.png"))); // NOI18N
        getContentPane().add(statusBar);
        statusBar.setBounds(630, 10, 600, 60);

        sakitStat2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        sakitStat2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sakitStat2.setText("sakit");
        getContentPane().add(sakitStat2);
        sakitStat2.setBounds(310, 380, 70, 40);

        laparStat2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        laparStat2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        laparStat2.setText("lapar");
        getContentPane().add(laparStat2);
        laparStat2.setBounds(310, 410, 70, 40);

        sakitStat3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        sakitStat3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sakitStat3.setText("sakit");
        getContentPane().add(sakitStat3);
        sakitStat3.setBounds(890, 380, 70, 40);

        laparStat3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        laparStat3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        laparStat3.setText("lapar");
        getContentPane().add(laparStat3);
        laparStat3.setBounds(890, 410, 70, 40);

        sakitStat4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        sakitStat4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sakitStat4.setText("sakit");
        getContentPane().add(sakitStat4);
        sakitStat4.setBounds(920, 260, 70, 40);

        laparStat4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        laparStat4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        laparStat4.setText("lapar");
        getContentPane().add(laparStat4);
        laparStat4.setBounds(920, 290, 70, 40);

        sakitStat5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        sakitStat5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sakitStat5.setText("sakit");
        getContentPane().add(sakitStat5);
        sakitStat5.setBounds(880, 130, 70, 40);

        laparStat5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        laparStat5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        laparStat5.setText("lapar");
        getContentPane().add(laparStat5);
        laparStat5.setBounds(880, 160, 70, 40);

        sakitStat1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        sakitStat1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sakitStat1.setText("sakit");
        getContentPane().add(sakitStat1);
        sakitStat1.setBounds(250, 260, 70, 40);

        laparStat1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        laparStat1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        laparStat1.setText("lapar");
        getContentPane().add(laparStat1);
        laparStat1.setBounds(250, 290, 70, 40);

        laparStat.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        laparStat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        laparStat.setText("lapar");
        getContentPane().add(laparStat);
        laparStat.setBounds(320, 130, 70, 40);

        sakitStat.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        sakitStat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sakitStat.setText("sakit");
        getContentPane().add(sakitStat);
        sakitStat.setBounds(320, 100, 70, 40);

        susuBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/susu_1.png"))); // NOI18N
        susuBtn1.setBorderPainted(false);
        susuBtn1.setContentAreaFilled(false);
        susuBtn1.setFocusable(false);
        susuBtn1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/susu rollover.png"))); // NOI18N
        getContentPane().add(susuBtn1);
        susuBtn1.setBounds(0, 220, 80, 70);

        susuBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/susu_1.png"))); // NOI18N
        susuBtn2.setBorderPainted(false);
        susuBtn2.setContentAreaFilled(false);
        susuBtn2.setFocusable(false);
        susuBtn2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/susu rollover.png"))); // NOI18N
        getContentPane().add(susuBtn2);
        susuBtn2.setBounds(80, 360, 80, 70);

        susuBtn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/susu_1.png"))); // NOI18N
        susuBtn3.setBorderPainted(false);
        susuBtn3.setContentAreaFilled(false);
        susuBtn3.setFocusable(false);
        susuBtn3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/susu rollover.png"))); // NOI18N
        getContentPane().add(susuBtn3);
        susuBtn3.setBounds(1120, 370, 80, 70);

        susuBtn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/susu_1.png"))); // NOI18N
        susuBtn4.setBorderPainted(false);
        susuBtn4.setContentAreaFilled(false);
        susuBtn4.setFocusable(false);
        susuBtn4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/susu rollover.png"))); // NOI18N
        getContentPane().add(susuBtn4);
        susuBtn4.setBounds(1160, 240, 80, 70);

        susuBtn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/susu_1.png"))); // NOI18N
        susuBtn5.setBorderPainted(false);
        susuBtn5.setContentAreaFilled(false);
        susuBtn5.setFocusable(false);
        susuBtn5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/susu rollover.png"))); // NOI18N
        getContentPane().add(susuBtn5);
        susuBtn5.setBounds(1110, 120, 80, 70);

        susuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/susu_1.png"))); // NOI18N
        susuBtn.setBorderPainted(false);
        susuBtn.setContentAreaFilled(false);
        susuBtn.setFocusable(false);
        susuBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/susu rollover.png"))); // NOI18N
        getContentPane().add(susuBtn);
        susuBtn.setBounds(60, 90, 80, 70);

        suntikBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button  ikon suntikan.png"))); // NOI18N
        suntikBtn.setBorderPainted(false);
        suntikBtn.setContentAreaFilled(false);
        suntikBtn.setFocusable(false);
        suntikBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button  ikon suntikan roll over 2.png"))); // NOI18N
        getContentPane().add(suntikBtn);
        suntikBtn.setBounds(120, 90, 80, 70);

        obatBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button ikon obat.png"))); // NOI18N
        obatBtn.setBorderPainted(false);
        obatBtn.setContentAreaFilled(false);
        obatBtn.setFocusable(false);
        obatBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button ikon obat rollover 2.png"))); // NOI18N
        getContentPane().add(obatBtn);
        obatBtn.setBounds(190, 90, 70, 70);

        nutrisiBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button ikon nutrisi.png"))); // NOI18N
        nutrisiBtn.setAutoscrolls(true);
        nutrisiBtn.setBorderPainted(false);
        nutrisiBtn.setContentAreaFilled(false);
        nutrisiBtn.setFocusable(false);
        nutrisiBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button ikon nutrisi rollover 2.png"))); // NOI18N
        getContentPane().add(nutrisiBtn);
        nutrisiBtn.setBounds(250, 90, 70, 70);

        airBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button ikon minum.png"))); // NOI18N
        airBtn.setBorderPainted(false);
        airBtn.setContentAreaFilled(false);
        airBtn.setFocusable(false);
        airBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button ikon minum roll over.png"))); // NOI18N
        getContentPane().add(airBtn);
        airBtn.setBounds(390, 200, 120, 80);

        makanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/IKON makan.png"))); // NOI18N
        makanBtn.setBorderPainted(false);
        makanBtn.setContentAreaFilled(false);
        makanBtn.setFocusable(false);
        makanBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/IKON makan rollover.png"))); // NOI18N
        getContentPane().add(makanBtn);
        makanBtn.setBounds(400, 130, 110, 80);

        tempatMakan6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tempat makan kanan.png"))); // NOI18N
        tempatMakan6.setBorderPainted(false);
        tempatMakan6.setContentAreaFilled(false);
        tempatMakan6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tempatMakan6.setFocusable(false);
        tempatMakan6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tempat makan rollover kanan.png"))); // NOI18N
        getContentPane().add(tempatMakan6);
        tempatMakan6.setBounds(810, 170, 100, 100);

        tempatMakan5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tempat makan kanan.png"))); // NOI18N
        tempatMakan5.setBorderPainted(false);
        tempatMakan5.setContentAreaFilled(false);
        tempatMakan5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tempatMakan5.setFocusable(false);
        tempatMakan5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tempat makan rollover kanan.png"))); // NOI18N
        getContentPane().add(tempatMakan5);
        tempatMakan5.setBounds(810, 290, 100, 100);

        tempatMakan4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tempat makan kanan.png"))); // NOI18N
        tempatMakan4.setBorderPainted(false);
        tempatMakan4.setContentAreaFilled(false);
        tempatMakan4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tempatMakan4.setFocusable(false);
        tempatMakan4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tempat makan rollover kanan.png"))); // NOI18N
        getContentPane().add(tempatMakan4);
        tempatMakan4.setBounds(810, 400, 100, 90);

        tempatMakan3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tempat makan.png"))); // NOI18N
        tempatMakan3.setBorderPainted(false);
        tempatMakan3.setContentAreaFilled(false);
        tempatMakan3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tempatMakan3.setFocusable(false);
        tempatMakan3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tempat makan rollover.png"))); // NOI18N
        getContentPane().add(tempatMakan3);
        tempatMakan3.setBounds(350, 390, 110, 100);

        tempatMakan2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tempat makan.png"))); // NOI18N
        tempatMakan2.setBorderPainted(false);
        tempatMakan2.setContentAreaFilled(false);
        tempatMakan2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tempatMakan2.setFocusable(false);
        tempatMakan2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tempat makan rollover.png"))); // NOI18N
        getContentPane().add(tempatMakan2);
        tempatMakan2.setBounds(350, 280, 110, 100);

        tempatMakan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tempat makan.png"))); // NOI18N
        tempatMakan1.setBorderPainted(false);
        tempatMakan1.setContentAreaFilled(false);
        tempatMakan1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tempatMakan1.setFocusable(false);
        tempatMakan1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tempatMakan1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tempat makan rollover.png"))); // NOI18N
        getContentPane().add(tempatMakan1);
        tempatMakan1.setBounds(350, 160, 110, 100);

        tempatMakan0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tempat makan kanan.png"))); // NOI18N
        tempatMakan0.setBorderPainted(false);
        tempatMakan0.setContentAreaFilled(false);
        tempatMakan0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tempatMakan0.setFocusable(false);
        tempatMakan0.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tempat makan rollover kanan.png"))); // NOI18N
        getContentPane().add(tempatMakan0);
        tempatMakan0.setBounds(510, 90, 100, 115);

        sapi0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sapi anakan.png"))); // NOI18N
        sapi0.setBorderPainted(false);
        sapi0.setContentAreaFilled(false);
        sapi0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sapi0.setFocusable(false);
        sapi0.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sapi anakan rollover.png"))); // NOI18N
        getContentPane().add(sapi0);
        sapi0.setBounds(60, 200, 90, 90);

        sapi6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Sapi dewasa.png"))); // NOI18N
        sapi6.setBorderPainted(false);
        sapi6.setContentAreaFilled(false);
        sapi6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sapi6.setFocusable(false);
        getContentPane().add(sapi6);
        sapi6.setBounds(910, 150, 220, 140);

        sapi5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Sapi dewasa.png"))); // NOI18N
        sapi5.setBorderPainted(false);
        sapi5.setContentAreaFilled(false);
        sapi5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sapi5.setFocusable(false);
        getContentPane().add(sapi5);
        sapi5.setBounds(980, 260, 220, 140);

        sapi4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Sapi dewasa.png"))); // NOI18N
        sapi4.setBorderPainted(false);
        sapi4.setContentAreaFilled(false);
        sapi4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sapi4.setFocusable(false);
        getContentPane().add(sapi4);
        sapi4.setBounds(920, 380, 230, 140);

        sapi3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sapi dalam kandang.png"))); // NOI18N
        sapi3.setBorderPainted(false);
        sapi3.setContentAreaFilled(false);
        sapi3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sapi3.setFocusable(false);
        getContentPane().add(sapi3);
        sapi3.setBounds(150, 390, 200, 113);

        sapi2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sapi dalam kandang.png"))); // NOI18N
        sapi2.setBorderPainted(false);
        sapi2.setContentAreaFilled(false);
        sapi2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sapi2.setFocusable(false);
        getContentPane().add(sapi2);
        sapi2.setBounds(60, 270, 220, 113);

        sapi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sapi dalam kandang.png"))); // NOI18N
        sapi1.setBorderPainted(false);
        sapi1.setContentAreaFilled(false);
        sapi1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sapi1.setFocusable(false);
        getContentPane().add(sapi1);
        sapi1.setBounds(110, 140, 230, 160);

        tulisanExit.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        tulisanExit.setText("EXIT");
        getContentPane().add(tulisanExit);
        tulisanExit.setBounds(602, 590, 80, 30);

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pintu keluar.png"))); // NOI18N
        homeButton.setBorderPainted(false);
        homeButton.setContentAreaFilled(false);
        homeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeButton.setFocusable(false);
        homeButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pintu keluar rollover.png"))); // NOI18N
        getContentPane().add(homeButton);
        homeButton.setBounds(566, 610, 150, 120);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dalam kandang bg.jpeg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 721);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_dalamKandang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_dalamKandang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_dalamKandang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_dalamKandang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_dalamKandang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton airBtn;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel iconsusu;
    private javax.swing.JLabel iconsusu1;
    private javax.swing.JLabel iconsusu2;
    private javax.swing.JLabel iconsusu3;
    private javax.swing.JLabel iconsusu4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel laparStat;
    private javax.swing.JLabel laparStat1;
    private javax.swing.JLabel laparStat2;
    private javax.swing.JLabel laparStat3;
    private javax.swing.JLabel laparStat4;
    private javax.swing.JLabel laparStat5;
    private javax.swing.JButton makanBtn;
    private javax.swing.JButton nutrisiBtn;
    private javax.swing.JLabel nutrisiCounter;
    private javax.swing.JButton obatBtn;
    private javax.swing.JLabel obatCounter;
    private javax.swing.JLabel rumputCounter;
    private javax.swing.JLabel sakitStat;
    private javax.swing.JLabel sakitStat1;
    private javax.swing.JLabel sakitStat2;
    private javax.swing.JLabel sakitStat3;
    private javax.swing.JLabel sakitStat4;
    private javax.swing.JLabel sakitStat5;
    private javax.swing.JButton sapi0;
    private javax.swing.JButton sapi1;
    private javax.swing.JButton sapi2;
    private javax.swing.JButton sapi3;
    private javax.swing.JButton sapi4;
    private javax.swing.JButton sapi5;
    private javax.swing.JButton sapi6;
    private javax.swing.JLabel statusBar;
    private javax.swing.JButton suntikBtn;
    private javax.swing.JLabel suntikanCounter;
    private javax.swing.JButton susuBtn;
    private javax.swing.JButton susuBtn1;
    private javax.swing.JButton susuBtn2;
    private javax.swing.JButton susuBtn3;
    private javax.swing.JButton susuBtn4;
    private javax.swing.JButton susuBtn5;
    private javax.swing.JLabel susuLabel;
    private javax.swing.JButton tempatMakan0;
    private javax.swing.JButton tempatMakan1;
    private javax.swing.JButton tempatMakan2;
    private javax.swing.JButton tempatMakan3;
    private javax.swing.JButton tempatMakan4;
    private javax.swing.JButton tempatMakan5;
    private javax.swing.JButton tempatMakan6;
    private javax.swing.JLabel tulisanExit;
    // End of variables declaration//GEN-END:variables
}
