/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import javax.swing.JButton;

/**
 *
 * @author Rangora
 */
public class v_help extends javax.swing.JFrame {

    /**
     * Creates new form Help
     */
    public v_help() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public JButton buttonKembali(){
        return btnKembali;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnKembali = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btnKembali.png"))); // NOI18N
        btnKembali.setBorderPainted(false);
        btnKembali.setContentAreaFilled(false);
        btnKembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKembali.setFocusable(false);
        btnKembali.setOpaque(false);
        btnKembali.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btnKembali rollover.png"))); // NOI18N
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 620, 250, -1));

        jLabel3.setFont(new java.awt.Font("DFPOP1-W9", 1, 24)); // NOI18N
        jLabel3.setText("...Bantuan GaMe...");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 240, 30));

        jLabel11.setFont(new java.awt.Font("DFPOP1-W9", 0, 12)); // NOI18N
        jLabel11.setText("7. Silahkan suntik sapi jika anda ingin mendapatkan tambahan sapi , tapi maksimal anak sapi dalam satu kandang hanya satu anak sapi saja");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, 1020, 30));

        jLabel12.setFont(new java.awt.Font("DFPOP1-W9", 0, 16)); // NOI18N
        jLabel12.setText("Perawatan sapi dikandang");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 230, 30));

        jLabel13.setFont(new java.awt.Font("DFPOP1-W9", 0, 12)); // NOI18N
        jLabel13.setText("1. Anda bisa membeli dan menjual produk di menu shop");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 450, 30));

        jLabel14.setFont(new java.awt.Font("DFPOP1-W9", 0, 12)); // NOI18N
        jLabel14.setText("2. Menu pesan saat anda klik \"buy\" akan berisi berapa satuan pembelian anda");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 470, 30));

        jLabel15.setFont(new java.awt.Font("DFPOP1-W9", 0, 12)); // NOI18N
        jLabel15.setText("3. Menu pesan saat anda klik \"sell\" akan berisi berapa satuan penjualan anda");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 470, 30));

        jLabel16.setFont(new java.awt.Font("DFPOP1-W9", 0, 12)); // NOI18N
        jLabel16.setText("4. Akan muncul pesan jika penjualan anda melebihi barang persediaan");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 470, 30));

        jLabel17.setFont(new java.awt.Font("DFPOP1-W9", 0, 12)); // NOI18N
        jLabel17.setText("5. Akan muncul pesan pada pembelian anda, jika coin yang dimiliki kurang dari harga");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 520, 30));

        jLabel18.setFont(new java.awt.Font("DFPOP1-W9", 0, 12)); // NOI18N
        jLabel18.setText("6. Silahkan tekan gambar rumah dipojok kiri bawah tampilan shop jika anda ingin  kembali ke game play");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 620, 30));

        jLabel19.setFont(new java.awt.Font("DFPOP1-W9", 0, 12)); // NOI18N
        jLabel19.setText("9. Silahkan anda bisa membeli kandang baru dengan klik papan \"beli kandang\" jika syarat dan ketentuan untuk membeli kandang sudah terpenuhi");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 860, 30));

        jLabel20.setFont(new java.awt.Font("DFPOP1-W9", 0, 12)); // NOI18N
        jLabel20.setText("1. Sapi akan berubah warna menjadi orange mudah ketika sapi dalam kondisi lapar");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 620, 30));

        jLabel22.setFont(new java.awt.Font("DFPOP1-W9", 0, 12)); // NOI18N
        jLabel22.setText("2. Sapi akan berubah warna menjadi orange tua ketika sapi dalam kondisi sakit");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 620, 30));

        jLabel21.setFont(new java.awt.Font("DFPOP1-W9", 0, 16)); // NOI18N
        jLabel21.setText("Game Play :");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 130, 30));

        jLabel23.setFont(new java.awt.Font("DFPOP1-W9", 0, 12)); // NOI18N
        jLabel23.setText("3. Klik sapi untuk menampilkan beberapa opsi fitur perawatan sapi");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 620, 30));

        jLabel24.setFont(new java.awt.Font("DFPOP1-W9", 0, 12)); // NOI18N
        jLabel24.setText("4. Klik tempat makan jika anda ingin memberi sapi makan");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 620, 30));

        jLabel25.setFont(new java.awt.Font("DFPOP1-W9", 0, 12)); // NOI18N
        jLabel25.setText("5. Silahkan ambil susu hasil produksi sapi anda , karena jika anda telat mengambilnya atau tidak diambil maka tingkat sakit sapi +25");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 810, 30));

        jLabel26.setFont(new java.awt.Font("DFPOP1-W9", 0, 12)); // NOI18N
        jLabel26.setText("6. Silahkan klik anak sapi yang baru dilahirkan untuk dipindahkan otomatis ke kandang kecil, jika tidak dipindah maka sapi kecil bisa mati dalam durasi 20 detik kedepan");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 1020, 30));

        jLabel27.setFont(new java.awt.Font("DFPOP1-W9", 0, 12)); // NOI18N
        jLabel27.setText("7. Tombol \"cancel\" digunakan jika anda ingin membatalkan transaksi ");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 620, 30));

        jLabel28.setFont(new java.awt.Font("DFPOP1-W9", 0, 12)); // NOI18N
        jLabel28.setText("8. Silahkan ambil atau klik rumput yang tumbuh dihalaman anda, karena akan menambah persediaan rumput anda");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 670, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background View Help 2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        setBounds(0, 0, 1280, 720);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_help().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
