/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import javax.swing.JButton;

/**
 *
 * @author Rangora
 */
public class v_inventori extends javax.swing.JFrame {

    /**
     * Creates new form v_aset
     */
    public v_inventori() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public JButton kembaliBtn(){
        return kembali;
    }
    
    public void setTeksSapiKecil(String teks){
        sapiKecilCount.setText(teks);
    }
    public void setTeksSuntikan(String teks){
        suntikanCount.setText(teks);
    }
    public void setTeksRumput(String teks){
        rumputCount.setText(teks);
    }
    public void setTeksSusu(String teks){
        susuCount.setText(teks);
    }
    public void setTeksObat(String teks){
        obatCount.setText(teks);
    }
    public void setTeksNutrisi(String teks){
        nutrisiCount.setText(teks);
    }
    public void setTeksKandang(String teks){
        kandangCount.setText(teks);
    }
    public void setTeksSapiBesar(String teks){
        sapiBesarCount.setText(teks);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        obatCount = new javax.swing.JLabel();
        suntikanCount = new javax.swing.JLabel();
        nutrisiCount = new javax.swing.JLabel();
        rumputCount = new javax.swing.JLabel();
        susuCount = new javax.swing.JLabel();
        kandangCount = new javax.swing.JLabel();
        sapiBesarCount = new javax.swing.JLabel();
        sapiKecilCount = new javax.swing.JLabel();
        kembali = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        obatCount.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        obatCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        obatCount.setText("jLabel1");
        getContentPane().add(obatCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 70, 30));

        suntikanCount.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        suntikanCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        suntikanCount.setText("jLabel1");
        getContentPane().add(suntikanCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 70, 30));

        nutrisiCount.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        nutrisiCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nutrisiCount.setText("jLabel1");
        getContentPane().add(nutrisiCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 70, 30));

        rumputCount.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        rumputCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rumputCount.setText("jLabel1");
        getContentPane().add(rumputCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 70, 30));

        susuCount.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        susuCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        susuCount.setText("jLabel1");
        getContentPane().add(susuCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 250, 70, 30));

        kandangCount.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        kandangCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kandangCount.setText("jLabel1");
        getContentPane().add(kandangCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 420, 70, 30));

        sapiBesarCount.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        sapiBesarCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sapiBesarCount.setText("jLabel1");
        getContentPane().add(sapiBesarCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 420, 70, 30));

        sapiKecilCount.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        sapiKecilCount.setText("jLabel1");
        getContentPane().add(sapiKecilCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 254, 70, 30));

        kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btnKembali.png"))); // NOI18N
        kembali.setBorderPainted(false);
        kembali.setContentAreaFilled(false);
        kembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kembali.setFocusPainted(false);
        kembali.setFocusable(false);
        kembali.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btnKembali rollover.png"))); // NOI18N
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 590, 240, 60));

        bg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg_aset.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_inventori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_inventori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_inventori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_inventori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_inventori().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel kandangCount;
    private javax.swing.JButton kembali;
    private javax.swing.JLabel nutrisiCount;
    private javax.swing.JLabel obatCount;
    private javax.swing.JLabel rumputCount;
    private javax.swing.JLabel sapiBesarCount;
    private javax.swing.JLabel sapiKecilCount;
    private javax.swing.JLabel suntikanCount;
    private javax.swing.JLabel susuCount;
    // End of variables declaration//GEN-END:variables
}
