/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Rangora
 */
public class v_login extends javax.swing.JFrame {

    /**
     * Creates new form v_login
     */
    public v_login() {
        initComponents();
        this.setLocationRelativeTo(this);
        createAccount.setLocationRelativeTo(this);
    }
    public void tombolLogin(ActionListener action){
        this.loginBtn.addActionListener(action);
    } 
    public void tombolCreateAccount(ActionListener action){
        this.createAccountBtn.addActionListener(action);
    } 
    
    //get text
    public String getUsername() {
        String username = usernameField.getText();
        return username;
    }
    public String getPassword() {
        String password = passwordField.getText();
        return password;
    }
    
    public String getUsernameCreate(){
        String username = createUsername.getText();
        return username;
    }
    
    public String getPasswordCreate(){
        String password = createPassword.getText();
        return password;
    }
    public void setUsernameCreate(String text){
        this.createUsername.setText(text);
    }
    
    public void setPasswordCreate(String text){
        this.createPassword.setText(text);
    }
    
    public JButton createButton(){
        return create;
    }
    
    public JButton cancelButton(){
        return createCancel;
    }
    
    public JFrame createAccount(){
        return createAccount;
    }
    
    //pop up ox
    public void tampilPesan(String pesan) {
        JOptionPane.showMessageDialog(this, pesan);
    }
    public int tampilYesNo(String pesan) {
        return JOptionPane.showConfirmDialog(this, pesan, null, JOptionPane.YES_NO_OPTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createAccount = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        createUsername = new javax.swing.JTextField();
        createPassword = new javax.swing.JPasswordField();
        createCancel = new javax.swing.JButton();
        create = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        createAccountBtn = new javax.swing.JButton();
        loginBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        createAccount.setUndecorated(true);
        createAccount.setResizable(false);
        createAccount.setSize(new java.awt.Dimension(470, 490));
        createAccount.setType(java.awt.Window.Type.POPUP);
        createAccount.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CREATE ACCOUNT");
        createAccount.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 320, 50));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel6.setText("Username");
        createAccount.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Password");
        createAccount.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 110, -1));
        createAccount.getContentPane().add(createUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 260, 40));

        createPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPasswordActionPerformed(evt);
            }
        });
        createAccount.getContentPane().add(createPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 260, 40));

        createCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cancel di popup.png"))); // NOI18N
        createCancel.setBorderPainted(false);
        createCancel.setContentAreaFilled(false);
        createCancel.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cancel di popup over.png"))); // NOI18N
        createAccount.getContentPane().add(createCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 170, -1));

        create.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/create button.png"))); // NOI18N
        create.setBorderPainted(false);
        create.setContentAreaFilled(false);
        create.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/create button rollover.png"))); // NOI18N
        createAccount.getContentPane().add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 170, 90));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background Create.png"))); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(470, 490));
        jLabel4.setMinimumSize(new java.awt.Dimension(470, 490));
        jLabel4.setPreferredSize(new java.awt.Dimension(470, 490));
        createAccount.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 490));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jLabel2.setText("Username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, 140, 30));

        jLabel3.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 330, 180, 30));

        usernameField.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        getContentPane().add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 280, 270, 40));

        passwordField.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 360, 270, 40));

        createAccountBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/createAkun.png"))); // NOI18N
        createAccountBtn.setBorderPainted(false);
        createAccountBtn.setContentAreaFilled(false);
        createAccountBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createAccountBtn.setFocusable(false);
        createAccountBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/createAkunOver.png"))); // NOI18N
        getContentPane().add(createAccountBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 290, 80));

        loginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Login button.png"))); // NOI18N
        loginBtn.setBorderPainted(false);
        loginBtn.setContentAreaFilled(false);
        loginBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/loginOver.png"))); // NOI18N
        getContentPane().add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 410, 290, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Background Login Dasar_1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton create;
    private javax.swing.JFrame createAccount;
    private javax.swing.JButton createAccountBtn;
    private javax.swing.JButton createCancel;
    private javax.swing.JPasswordField createPassword;
    private javax.swing.JTextField createUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
