/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Rangora
 */
public class v_shop extends javax.swing.JFrame {

    /**
     * Creates new form v_shop
     */
    public v_shop() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    public JLabel getSusuIcon() {
        return susuIcon;
    }

    public JLabel getSusuPrice() {
        return susuPrice;
    }

    public JLabel getBuyLabel() {
        return buyClicked;
    }

    public JLabel getSellLabel() {
        return sellClicked;
    }

    public JLabel getKoinIcon() {
        return koinIcon5;
    }

    public JButton getSusuButton() {
        return susuButton;
    }

    public JButton getBuyButton() {
        return buyButton;
    }

    public JButton getSellButton() {
        return sellButton;
    }

    public void homeButton(ActionListener action) {
        this.homeButton.addActionListener(action);
    }

    public void rumputButton(ActionListener action) {
        this.rumputButton.addActionListener(action);
    }

    public void sapiButton(ActionListener action) {
        this.sapiButton.addActionListener(action);
    }

    public void nutrisiButton(ActionListener action) {
        this.nutrisiButton.addActionListener(action);
    }

    public void suntikanButton(ActionListener action) {
        this.suntikanButton.addActionListener(action);
    }

    public void obatButton(ActionListener action) {
        this.obatButton.addActionListener(action);
    }

    public void susuButton(ActionListener action) {
        this.susuButton.addActionListener(action);
    }

    public int setSapi(int text) {
        this.sapiCounter.setText(text + "");
        return text;
    }

    public int setKoin(int text) {
        this.koinCounter.setText(text + "");
        return text;
    }

    public int setRumput(int text) {
        this.rumputCounter.setText(text + "");
        return text;
    }

    public int setNutrisi(int text) {
        this.nutrisiCounter.setText(text + "");
        return text;
    }

    public int setSuntikan(int text) {
        this.suntikanCounter.setText(text + "");
        return text;
    }

    public int setObat(int text) {
        this.obatCounter.setText(text + "");
        return text;
    }

    public int setSusu(int text) {
        this.susuCounter.setText(text + "");
        return text;
    }

    public int setRumputPrice(int text) {
        this.rumputPrice.setText(text + "");
        return text;
    }

    public int setSapiPrice(int text) {
        this.sapiPrice.setText(text + "");
        return text;
    }

    public int setNutrisiPrice(int text) {
        this.nutrisiPrice.setText(text + "");
        return text;
    }

    public int setSuntikPrice(int text) {
        this.suntikPrice.setText(text + "");
        return text;
    }

    public int setObatPrice(int text) {
        this.obatPrice.setText(text + "");
        return text;
    }

    public int setSusuPrice(int text) {
        this.susuPrice.setText(text + "");
        return text;
    }

    public void tampilPesan(String pesan) {
        JOptionPane.showMessageDialog(this, pesan);
    }

    public int tampilYesNo(String pesan) {
        return JOptionPane.showConfirmDialog(this, pesan, null, JOptionPane.YES_NO_OPTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sellClicked = new javax.swing.JLabel();
        buyClicked = new javax.swing.JLabel();
        sapiCounter = new javax.swing.JLabel();
        susuCounter = new javax.swing.JLabel();
        obatCounter = new javax.swing.JLabel();
        suntikanCounter = new javax.swing.JLabel();
        nutrisiCounter = new javax.swing.JLabel();
        rumputCounter = new javax.swing.JLabel();
        susuButton = new javax.swing.JButton();
        obatButton = new javax.swing.JButton();
        suntikanButton = new javax.swing.JButton();
        nutrisiButton = new javax.swing.JButton();
        sapiButton = new javax.swing.JButton();
        rumputButton = new javax.swing.JButton();
        sapiStatus = new javax.swing.JLabel();
        susuStatus = new javax.swing.JLabel();
        obatStatus = new javax.swing.JLabel();
        suntikanStatus = new javax.swing.JLabel();
        nutrisiStatus = new javax.swing.JLabel();
        rumputStatus = new javax.swing.JLabel();
        statusBar = new javax.swing.JLabel();
        susuPrice = new javax.swing.JLabel();
        obatPrice = new javax.swing.JLabel();
        suntikPrice = new javax.swing.JLabel();
        nutrisiPrice = new javax.swing.JLabel();
        sapiPrice = new javax.swing.JLabel();
        rumputPrice = new javax.swing.JLabel();
        koinIcon1 = new javax.swing.JLabel();
        koinIcon2 = new javax.swing.JLabel();
        koinIcon3 = new javax.swing.JLabel();
        koinIcon4 = new javax.swing.JLabel();
        koinIcon5 = new javax.swing.JLabel();
        koinIcon = new javax.swing.JLabel();
        buyButton = new javax.swing.JButton();
        sellButton = new javax.swing.JButton();
        koinCounter = new javax.swing.JLabel();
        susuIcon = new javax.swing.JLabel();
        medicIcon = new javax.swing.JLabel();
        suntikIcon = new javax.swing.JLabel();
        nutrisiIcon = new javax.swing.JLabel();
        sapiIcon = new javax.swing.JLabel();
        rumputIcon = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sellClicked.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sellClicked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sell button click.png"))); // NOI18N
        getContentPane().add(sellClicked, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 190, 70));

        buyClicked.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buyClicked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/buy button click.png"))); // NOI18N
        getContentPane().add(buyClicked, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 180, 70));

        sapiCounter.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        sapiCounter.setText("Sapi");
        getContentPane().add(sapiCounter, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 60, 40));

        susuCounter.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        susuCounter.setText("susu");
        getContentPane().add(susuCounter, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 14, 50, 30));

        obatCounter.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        obatCounter.setText("obat");
        getContentPane().add(obatCounter, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 60, 40));

        suntikanCounter.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        suntikanCounter.setText("suntikan");
        getContentPane().add(suntikanCounter, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 60, 40));

        nutrisiCounter.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        nutrisiCounter.setText("nutrisi");
        getContentPane().add(nutrisiCounter, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 60, 40));

        rumputCounter.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        rumputCounter.setText("rumput");
        getContentPane().add(rumputCounter, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 60, 40));

        susuButton.setBorderPainted(false);
        susuButton.setContentAreaFilled(false);
        susuButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        susuButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bottomm pilihan dalam shop.png"))); // NOI18N
        getContentPane().add(susuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, 500, 110));

        obatButton.setBorderPainted(false);
        obatButton.setContentAreaFilled(false);
        obatButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        obatButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bottomm pilihan dalam shop.png"))); // NOI18N
        getContentPane().add(obatButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, 500, 110));

        suntikanButton.setBorderPainted(false);
        suntikanButton.setContentAreaFilled(false);
        suntikanButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        suntikanButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bottomm pilihan dalam shop.png"))); // NOI18N
        getContentPane().add(suntikanButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, 500, 120));

        nutrisiButton.setBorderPainted(false);
        nutrisiButton.setContentAreaFilled(false);
        nutrisiButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nutrisiButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bottomm pilihan dalam shop.png"))); // NOI18N
        getContentPane().add(nutrisiButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 490, 110));

        sapiButton.setBorderPainted(false);
        sapiButton.setContentAreaFilled(false);
        sapiButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sapiButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bottomm pilihan dalam shop.png"))); // NOI18N
        sapiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sapiButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sapiButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 490, 110));

        rumputButton.setBorderPainted(false);
        rumputButton.setContentAreaFilled(false);
        rumputButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rumputButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bottomm pilihan dalam shop.png"))); // NOI18N
        getContentPane().add(rumputButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 490, 120));

        sapiStatus.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        sapiStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sapiStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sapi dewasa Cilik.png"))); // NOI18N
        sapiStatus.setText(":");
        getContentPane().add(sapiStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 10, 60, 40));

        susuStatus.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        susuStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        susuStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/susu cilik.png"))); // NOI18N
        susuStatus.setText(":");
        getContentPane().add(susuStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 10, 60, 40));

        obatStatus.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        obatStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        obatStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/medic Cilik.png"))); // NOI18N
        obatStatus.setText(":");
        getContentPane().add(obatStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 50, 40));

        suntikanStatus.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        suntikanStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        suntikanStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/suntik Cilik.png"))); // NOI18N
        suntikanStatus.setText(":");
        getContentPane().add(suntikanStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, 50, 40));

        nutrisiStatus.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        nutrisiStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nutrisiStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nutrisi Cilik.png"))); // NOI18N
        nutrisiStatus.setText(":");
        getContentPane().add(nutrisiStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 50, 40));

        rumputStatus.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        rumputStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rumputStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rumput cilik.png"))); // NOI18N
        rumputStatus.setText(":");
        getContentPane().add(rumputStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, 40));

        statusBar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/status Bar di shop.png"))); // NOI18N
        statusBar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(statusBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 600, 40));

        susuPrice.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        susuPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        susuPrice.setText("1000");
        getContentPane().add(susuPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 480, 150, 30));

        obatPrice.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        obatPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        obatPrice.setText("1000");
        getContentPane().add(obatPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 340, 150, 30));

        suntikPrice.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        suntikPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        suntikPrice.setText("1000");
        getContentPane().add(suntikPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 210, 150, 30));

        nutrisiPrice.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        nutrisiPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nutrisiPrice.setText("1000");
        getContentPane().add(nutrisiPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 150, 30));

        sapiPrice.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        sapiPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        sapiPrice.setText("1000");
        getContentPane().add(sapiPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 150, 30));

        rumputPrice.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        rumputPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rumputPrice.setText("1000");
        getContentPane().add(rumputPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 150, 30));

        koinIcon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        koinIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/koin.png"))); // NOI18N
        getContentPane().add(koinIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 70, 70));

        koinIcon2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        koinIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/koin.png"))); // NOI18N
        getContentPane().add(koinIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, 70, 70));

        koinIcon3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        koinIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/koin.png"))); // NOI18N
        getContentPane().add(koinIcon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 190, 70, 70));

        koinIcon4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        koinIcon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/koin.png"))); // NOI18N
        getContentPane().add(koinIcon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 320, 70, 70));

        koinIcon5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        koinIcon5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/koin.png"))); // NOI18N
        getContentPane().add(koinIcon5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 460, 70, 70));

        koinIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        koinIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/koin.png"))); // NOI18N
        getContentPane().add(koinIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 70, 70));

        buyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button Buy.png"))); // NOI18N
        buyButton.setBorderPainted(false);
        buyButton.setContentAreaFilled(false);
        buyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buyButton.setFocusable(false);
        buyButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buyButton.setRequestFocusEnabled(false);
        buyButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/buy button click.png"))); // NOI18N
        buyButton.setSelected(true);
        buyButton.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(buyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 190, 70));

        sellButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Button Sell.png"))); // NOI18N
        sellButton.setBorderPainted(false);
        sellButton.setContentAreaFilled(false);
        sellButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sellButton.setDefaultCapable(false);
        sellButton.setFocusable(false);
        sellButton.setRequestFocusEnabled(false);
        sellButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sell button click.png"))); // NOI18N
        sellButton.setSelected(true);
        sellButton.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(sellButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 190, 70));

        koinCounter.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        koinCounter.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        koinCounter.setText("coin");
        getContentPane().add(koinCounter, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 90, 170, 50));

        susuIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        susuIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/susu.png"))); // NOI18N
        getContentPane().add(susuIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 440, 110, 110));

        medicIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        medicIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/medic.png"))); // NOI18N
        getContentPane().add(medicIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 300, 110, 110));

        suntikIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        suntikIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/suntik sapi.png"))); // NOI18N
        getContentPane().add(suntikIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 170, 110, 100));

        nutrisiIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nutrisiIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nutrisi.png"))); // NOI18N
        getContentPane().add(nutrisiIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 140, 100));

        sapiIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Sapi dewasa.png"))); // NOI18N
        getContentPane().add(sapiIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 160, 90));

        rumputIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Rumput.png"))); // NOI18N
        getContentPane().add(rumputIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 150, 100));

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home button.png"))); // NOI18N
        homeButton.setBorderPainted(false);
        homeButton.setContentAreaFilled(false);
        homeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeButton.setRequestFocusEnabled(false);
        homeButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/homeOver.png"))); // NOI18N
        homeButton.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 520, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background shop.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sapiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sapiButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sapiButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_shop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton buyButton;
    private javax.swing.JLabel buyClicked;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel koinCounter;
    private javax.swing.JLabel koinIcon;
    private javax.swing.JLabel koinIcon1;
    private javax.swing.JLabel koinIcon2;
    private javax.swing.JLabel koinIcon3;
    private javax.swing.JLabel koinIcon4;
    private javax.swing.JLabel koinIcon5;
    private javax.swing.JLabel medicIcon;
    private javax.swing.JButton nutrisiButton;
    private javax.swing.JLabel nutrisiCounter;
    private javax.swing.JLabel nutrisiIcon;
    private javax.swing.JLabel nutrisiPrice;
    private javax.swing.JLabel nutrisiStatus;
    private javax.swing.JButton obatButton;
    private javax.swing.JLabel obatCounter;
    private javax.swing.JLabel obatPrice;
    private javax.swing.JLabel obatStatus;
    private javax.swing.JButton rumputButton;
    private javax.swing.JLabel rumputCounter;
    private javax.swing.JLabel rumputIcon;
    private javax.swing.JLabel rumputPrice;
    private javax.swing.JLabel rumputStatus;
    private javax.swing.JButton sapiButton;
    private javax.swing.JLabel sapiCounter;
    private javax.swing.JLabel sapiIcon;
    private javax.swing.JLabel sapiPrice;
    private javax.swing.JLabel sapiStatus;
    private javax.swing.JButton sellButton;
    private javax.swing.JLabel sellClicked;
    private javax.swing.JLabel statusBar;
    private javax.swing.JLabel suntikIcon;
    private javax.swing.JLabel suntikPrice;
    private javax.swing.JButton suntikanButton;
    private javax.swing.JLabel suntikanCounter;
    private javax.swing.JLabel suntikanStatus;
    private javax.swing.JButton susuButton;
    private javax.swing.JLabel susuCounter;
    private javax.swing.JLabel susuIcon;
    private javax.swing.JLabel susuPrice;
    private javax.swing.JLabel susuStatus;
    // End of variables declaration//GEN-END:variables
}
