/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import java.awt.Button;
import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Rangora
 */
public class v_shopPopUp extends javax.swing.JFrame {

    /**
     * Creates new form v_shopPopUp
     */
    public v_shopPopUp() {
        initComponents();
        this.setLocationRelativeTo(this);
    }
    public JButton getButtonKiri(){
        return leftButton;
    }
    public JButton getButtonBuy(){
        return buyButton;
    }
    public JButton getButtonSell(){
        return sellButton;
    }
    public void arahKiri(ActionListener action) {
        this.leftButton.addActionListener(action);
    }

    public void arahKanan(ActionListener action) {
        this.rightButton.addActionListener(action);
    }

    public void tombolCancel(ActionListener action) {
        this.cancelButton.addActionListener(action);
    }
    public JLabel setGambar(){
        return icon;
    }

    public void tombolBuy(ActionListener action) {
        this.buyButton.addActionListener(action);
    }
    public void tombolSell(ActionListener action) {
        this.sellButton.addActionListener(action);
    }

    public String getTeksBuy() {
        return buyButton.getText();
    }

    public int getTeksJumlah() {
        String hasil = jumlah.getText();
        return Integer.valueOf(hasil);
    }

    public void setTeksBuy(String teks) {
        buyButton.setText(teks);
    }

    public void setTeksJumlah(String teks) {
        jumlah.setText(teks);
    }

    public void tampilPesan(String pesan) {
        JOptionPane.showMessageDialog(this, pesan);
    }

    public int tampilYesNo(String pesan) {
        return JOptionPane.showConfirmDialog(this, pesan, null, JOptionPane.YES_NO_OPTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        icon = new javax.swing.JLabel();
        jumlah = new javax.swing.JLabel();
        sellButton = new javax.swing.JButton();
        buyButton = new javax.swing.JButton();
        leftButton = new javax.swing.JButton();
        rightButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.red);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 160, 120));

        jumlah.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jumlah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jumlah.setText("1");
        getContentPane().add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 232, 110, 40));

        sellButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sell di popup.png"))); // NOI18N
        sellButton.setBorderPainted(false);
        sellButton.setContentAreaFilled(false);
        sellButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sellButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sell di popup over.png"))); // NOI18N
        sellButton.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(sellButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 180, 70));

        buyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/buy di popup.png"))); // NOI18N
        buyButton.setBorderPainted(false);
        buyButton.setContentAreaFilled(false);
        buyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buyButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/buy di popup over.png"))); // NOI18N
        getContentPane().add(buyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 160, 70));

        leftButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/panah kiri.png"))); // NOI18N
        leftButton.setBorderPainted(false);
        leftButton.setContentAreaFilled(false);
        leftButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        leftButton.setRequestFocusEnabled(false);
        leftButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/panah kiri over.png"))); // NOI18N
        leftButton.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(leftButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 212, 90, 80));

        rightButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/panah kanan.png"))); // NOI18N
        rightButton.setBorderPainted(false);
        rightButton.setContentAreaFilled(false);
        rightButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rightButton.setRequestFocusEnabled(false);
        rightButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/panah kanan Over.png"))); // NOI18N
        rightButton.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(rightButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 212, 90, 80));

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cancel di popup.png"))); // NOI18N
        cancelButton.setBorderPainted(false);
        cancelButton.setContentAreaFilled(false);
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cancel di popup over.png"))); // NOI18N
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 160, 70));

        backGround.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background PopUp.png"))); // NOI18N
        backGround.setAlignmentY(0.0F);
        backGround.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(backGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_shopPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_shopPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_shopPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_shopPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_shopPopUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backGround;
    private javax.swing.JButton buyButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel jumlah;
    private javax.swing.JButton leftButton;
    private javax.swing.JButton rightButton;
    private javax.swing.JButton sellButton;
    // End of variables declaration//GEN-END:variables
}
